[package]
name = "mzbatch_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"  
quick-xml = {version="0.36.0", features = ["serialize", "serde-types"]}
